spring.application.name=bank-api

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_api
spring.datasource.username=postgres
spring.datasource.password=14121992

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081